-- Snowflake Table Definitions for Police Use of Force Dataset 2023
-- Generated based on CSV file analysis

-- =============================================================================
-- 1. EN_DATA_DICTIONARY_2023 Table
-- This table contains metadata about variables in the other tables
-- =============================================================================
CREATE OR REPLACE TABLE ON_POLICE_USE_OF_FORCE.DATA_DICTIONARY.EN_DATA_DICTIONARY_2023 (
    FILE_NAME VARCHAR,
    VARIABLE_NAME VARCHAR,
    VARIABLE_LABEL VARCHAR,
    VARIABLE_DEFINITION VARCHAR,
    DATA_VALUES VARCHAR,
    REQUIREMENT_STATUS_IN_USE_OF_FORCE_REPORT VARCHAR,
    ADDITIONAL_NOTES VARCHAR,
    DATA_TYPE VARCHAR,
    DATA_FORMAT VARCHAR,
    MEASUREMENT_LEVEL VARCHAR,
    RECODED_VARIABLE_FLAG VARCHAR,
    RECODED_VARIABLE_NOTES VARCHAR
);

-- =============================================================================
-- 2. POLICE_USE_OF_FORCE_CYCLE_PROBE_RECORDS_2023 Table
-- This table contains conducted energy weapon cartridge probe cycle data
-- =============================================================================
CREATE OR REPLACE TABLE UOF_CYCLE_PROBE_RECORDS_2023 (
    _ID VARCHAR,
    BATCH_FILE_NAME VARCHAR,
    INDIV_INDEX VARCHAR,
    CONDUCTED_ENERGY_WEAPON_CARTRIDGE_PROBE_CARTRIDGE_PROBE_CYCLES_CYC VARCHAR(100)
);

-- =============================================================================
-- 3. POLICE_USE_OF_FORCE_INDIVIDUAL_RECORDS_2023 Table
-- This table contains detailed individual-level data for use of force incidents
-- =============================================================================
CREATE OR REPLACE TABLE UOF_INDIVIDUAL_RECORDS_2023 (
    _ID VARCHAR,
    BATCH_FILE_NAME VARCHAR,
    INDIV_INDEX VARCHAR,
    RACE VARCHAR,
    DIFFICULTY_PERCEIVING VARCHAR,
    AGE_CATEGORY VARCHAR,
    GENDER VARCHAR,
    DISTANCE_BETWEEN_OFFICER_AND_INDIV VARCHAR,
    
    -- Reason for Use of Force (Boolean flags - 1 or NULL)
    REASON_USE_OF_FORCE_EFFECT_ARREST VARCHAR,
    REASON_USE_OF_FORCE_PREVENT_OFFENCE VARCHAR,
    REASON_USE_OF_FORCE_PREVENT_ESCAPE VARCHAR,
    REASON_USE_OF_FORCE_PROTECT_OTHER_OFFICERS VARCHAR,
    REASON_USE_OF_FORCE_PROTECT_PUBLIC VARCHAR,
    REASON_USE_OF_FORCE_PROTECT_SELF VARCHAR,
    REASON_USE_OF_FORCE_PROTECT_INDIV VARCHAR,
    REASON_USE_OF_FORCE_UNINTENTIONAL VARCHAR,
    REASON_USE_OF_FORCE_OTHER VARCHAR,
    
    -- Factors Influencing Response (Boolean flags)
    FACTORS_INFLUENCE_RESPONSE_NATURE_INCIDENT VARCHAR,
    FACTORS_INFLUENCE_RESPONSE_PAST_HISTORY VARCHAR,
    FACTORS_INFLUENCE_RESPONSE_PHYSICAL_SIZE_STRENGTH VARCHAR,
    FACTORS_INFLUENCE_RESPONSE_OTHER_FACTORS VARCHAR,
    
    -- Individual Actions (Boolean flags)
    INDIVIDUAL_ACTIONS_RESISTANT_PASSIVE VARCHAR,
    INDIVIDUAL_ACTIONS_RESISTANT_ACTIVE VARCHAR,
    INDIVIDUAL_ACTIONS_ASSAULTIVE VARCHAR,
    INDIVIDUAL_ACTIONS_SERIOUS_BODILY_HARM_DEATH VARCHAR,
    
    PERCEIVE_ACCESS_WEAPON VARCHAR,
    
    -- Officer Responses
    OFFICER_RESPONSES_DIRECTIONS_TO_COMPLY VARCHAR,
    OFFICER_RESPONSES_COMPLY VARCHAR,
    OFFICER_RESPONSES_ATTEMPT_DEESCALATION VARCHAR,
    
    -- Deescalation Techniques (Boolean flags)
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_COMMUNICATION VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_CONTAINMENT VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_COVER VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_DISTANCE VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_REPOSITIONING VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_TEAMWORK VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_TIME VARCHAR,
    OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_OTHER VARCHAR,
    
    OFFICER_RESPONSES_ASSIST_CTRL_BHVR VARCHAR(10),
    
    -- Officer Response Reasons (Boolean flags)
    OFFICER_RESPONSES_REASON_IMMINENT_THREAT VARCHAR,
    OFFICER_RESPONSES_REASON_ACTION_REQUIRED_IMMEDIATELY VARCHAR,
    OFFICER_RESPONSES_REASON_DEESCALATION_USED_OTHER_OFFICERS VARCHAR,
    OFFICER_RESPONSES_REASON_OTHER VARCHAR,
    
    -- Type of Force Used - Physical Control (Boolean flags)
    TYPE_FORCE_USED_PHYSICAL_CONTROL_CHECK VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_ESCORT_TECHNIQUES VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_GROUNDING VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_JOINT_LOCKS VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_PINNING VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_PRESSURE_POINTS VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_STRIKES VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_OTHER VARCHAR,
    TYPE_FORCE_USED_PHYSICAL_CONTROL_ASSIST_CTRL_BHVR VARCHAR,
    
    -- Type of Force Used - Intermediate Weapons (Boolean flags)
    TYPE_FORCE_USED_INTERM_WEAPON_CHECK VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_OC_CHECK VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_OC_ASSIST_CTRL_BHVR VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_BATON_CHECK VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_BATON_HARD VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_BATON_SOFT VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_BATON_ASSIST_CTRL_BHVR BOOLEAN,
    
    -- CEW (Conducted Energy Weapon) Related Fields
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_CHECK VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_ASSIST_CTRL_BHVR BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_CARTRIDGE_MALFUNCTION BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_DISCONNECT BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_INSUFFICIENT_PROBE_SPREAD BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_OPERATOR_ERROR BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_PROBE_MISS BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_WEAPON_MALFUNCTION BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_WHY_NOT_OTHER BOOLEAN,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_DRAWN VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_POINTED VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_DISCHARGED VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_DEPLOYMENT_MODE_CARTRIDGE VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_DEPLOYMENT_MODE_DRIVE_PUSH_STUN VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_DEPLOYMENT_MODE_THREE_POINT_CONTACT VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_DRIVE_PUSH_STUN_CYCLES VARCHAR,
    TYPE_FORCE_USED_INTERM_WEAPON_CEW_THREE_POINT_CONTACT_CYCLES VARCHAR,
    
    -- Less Lethal Firearms (Boolean flags)
    TYPE_FORCE_USED_LL_FIREARM_CHECK VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_SHOTGUN_CHECK VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_SHOTGUN_POINTED VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_SHOTGUN_DISCHARGED VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_SHOTGUN_ASSIST_CTRL_BHVR BOOLEAN,
    TYPE_FORCE_USED_LL_FIREARM_EXT_RANGE_IMPACT_WEAPON_CHECK VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_EXT_RANGE_IMPACT_WEAPON_POINTED VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_EXT_RANGE_IMPACT_WEAPON_DISCHARGED VARCHAR,
    TYPE_FORCE_USED_LL_FIREARM_EXT_RANGE_IMPACT_WEAPON_ASSIST_CTRL_BHVR BOOLEAN,
    
    -- Other Force Types
    TYPE_FORCE_USED_OTHER_CHECK VARCHAR,
    TYPE_FORCE_USED_OTHER_ASSIST_CTRL_BHVR BOOLEAN,
    
    -- Firearms (Boolean flags)
    TYPE_FORCE_USED_FIREARM_CHECK VARCHAR,
    TYPE_FORCE_USED_FIREARM_HANDGUN_CHECK VARCHAR,
    TYPE_FORCE_USED_FIREARM_HANDGUN_DRAWN VARCHAR,
    TYPE_FORCE_USED_FIREARM_HANDGUN_POINTED VARCHAR,
    TYPE_FORCE_USED_FIREARM_HANDGUN_DISCHARGED VARCHAR,
    TYPE_FORCE_USED_FIREARM_HANDGUN_ASSIST_CTRL_BHVR BOOLEAN,
    TYPE_FORCE_USED_FIREARM_RIFLE_CHECK VARCHAR,
    TYPE_FORCE_USED_FIREARM_RIFLE_POINTED VARCHAR,
    TYPE_FORCE_USED_FIREARM_RIFLE_DISCHARGED VARCHAR,
    TYPE_FORCE_USED_FIREARM_RIFLE_ASSIST_CTRL_BHVR BOOLEAN,
    TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_CHECK VARCHAR,
    TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_POINTED VARCHAR,
    TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_DISCHARGED VARCHAR,
    TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_ASSIST_CONTROLLING_BEHAVIOUR BOOLEAN,
    TYPE_FORCE_USED_FIREARM_ISSUE_POLICE_CHALLENGE BOOLEAN,
    TYPE_FORCE_USED_FIREARM_COMPLY BOOLEAN,
    TYPE_FORCE_USED_FIREARM_NO_CHALLENGE_WHY_NOT_NOT_VIABLE VARCHAR,
    TYPE_FORCE_USED_FIREARM_NO_CHALLENGE_WHY_NOT_ISSUED_BY_ANOTHER_OFFICER VARCHAR,
    TYPE_FORCE_USED_FIREARM_NO_CHALLENGE_WHY_NOT_OTHER VARCHAR,
    
    -- Individual Injuries
    INDIV_INJURIES_PHYSICAL_INJURIES VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_NO VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_FIRST_AID VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_MEDICAL_PERSONNEL_SCENE VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_ADMISSION_MEDICAL_FACILITY VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_MEDICAL_FACILITY VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_UNKNOWN VARCHAR,
    INDIVIDUAL_INJURIES_TREATMENT_OTHER VARCHAR
);

-- =============================================================================
-- 4. POLICE_USE_OF_FORCE_MAIN_RECORDS_2023 Table
-- This table contains the main incident records
-- =============================================================================
CREATE OR REPLACE TABLE UOF_MAIN_RECORDS_2023 (
    _ID VARCHAR,
    BATCH_FILE_NAME VARCHAR(50),
    POLICE_SERVICE_TYPE VARCHAR(50),
    POLICE_SERVICE VARCHAR(100),
    OPP_POLICE_SERVICE VARCHAR(100),
    INCIDENT_NUMBER VARCHAR(50),
    DATE DATE,
    APPROXIMATE_TIME_FORCE_APPLIED TIME,
    
    -- Location Types (Boolean flags)
    LOCATION_TYPE_RESIDENTIAL_BUILDING VARCHAR,
    LOCATION_TYPE_NON_RESIDENTIAL_BUILDING VARCHAR,
    LOCATION_TYPE_MOTOR_VEHICLE VARCHAR,
    LOCATION_TYPE_OPEN_SPACE VARCHAR,
    LOCATION_TYPE_PUBLIC_TRANSPORTATION VARCHAR,
    
    REPORT_TYPE VARCHAR(50),
    TYPE_TEAM VARCHAR(50),
    NUMBER_TEAM VARCHAR,
    ATTIRE VARCHAR(50),
    ASSIGNMENT_TYPE VARCHAR(200),
    INCIDENT_TYPE VARCHAR(200),
    
    -- Humane Destruction of Animal fields
    HUMANE_DESTRUCTION_ANIMAL_DISTANCE VARCHAR(100),
    HUMANE_DESTRUCTION_ANIMAL_HANDGUN VARCHAR,
    HUMANE_DESTRUCTION_ANIMAL_RIFLE VARCHAR,
    HUMANE_DESTRUCTION_ANIMAL_SHOTGUN VARCHAR,
    HUMANE_DESTRUCTION_ANIMAL_NUMBER_ROUNDS_DISCHARGED VARCHAR,
    
    INTERACTION_TYPE VARCHAR(100),
    NUMBER_INDIVIDUALS VARCHAR,
    NUMBER_OTHER_OFFICERS VARCHAR,
    
    -- Officer Involved Injuries
    OFFICER_INVOLVED_INJURIES_PHYSICAL_INJURIES VARCHAR(10),
    OFFICER_INVOLVED_INJURIES_TREATMENT_NO VARCHAR,
    OFFICER_INVOLVED_INJURIES_TREATMENT_FIRST_AID VARCHAR,
    OFFICER_INVOLVED_INJURIES_TREATMENT_MEDICAL_PERSONNEL_SCENE VARCHAR,
    OFFICER_INVOLVED_INJURIES_TREATMENT_ADMISSION_MEDICAL_FACILITY VARCHAR,
    OFFICER_INVOLVED_INJURIES_TREATMENT_MEDICAL_FACILITY VARCHAR,
    OFFICER_INVOLVED_INJURIES_TREATMENT_UNKNOWN VARCHAR,
    OFFICER_INVOLVED_INJURIES_TREATMENT_OTHER VARCHAR,
    
    -- No Interact Individual fields (Boolean flags)
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_EFFECT_ARREST VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_PREVENT_OFFENCE VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_PREVENT_ESCAPE VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_PROTECT_OTHER_OFFICERS VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_PROTECT_PUBLIC VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_PROTECT_SELF VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_PROTECT_INDIV VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_UNINTENTIONAL VARCHAR,
    NO_INTERACT_INDIV_REASON_USE_OF_FORCE_OTHER VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_CEW_CHECK VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_CEW_DISCHARGED VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_HANDGUN_CHECK VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_HANDGUN_DRAWN VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_HANDGUN_DISCHARGED VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_RIFLE_CHECK VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_RIFLE_DISCHARGED VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_CHECK VARCHAR,
    NO_INTERACT_INDIV_TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_DISCHARGED VARCHAR,
    
    -- No Individual Animal Only fields (Boolean flags)
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_EFFECT_ARREST VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_PREVENT_OFFENCE VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_PREVENT_ESCAPE VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_PROTECT_OTHER_OFFICERS VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_PROTECT_PUBLIC VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_PROTECT_SELF VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_PROTECT_INDIV VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_UNINTENTIONAL VARCHAR,
    NO_INDIV_ANIMAL_ONLY_REASON_USE_OF_FORCE_OTHER VARCHAR,
    NO_INDIV_ANIMAL_ONLY_TYPE_FORCE_USED_CEW VARCHAR,
    NO_INDIV_ANIMAL_ONLY_TYPE_FORCE_USED_FIREARM VARCHAR,
    
    INCLUSION_SOLGEN_ARA_ANALYSIS VARCHAR(10)
);

-- =============================================================================
-- 5. POLICE_USE_OF_FORCE_WEAPONS_RECORDS_2023 Table
-- This table contains weapon information linked to individuals in incidents
-- =============================================================================
CREATE OR REPLACE TABLE UOF_WEAPONS_RECORDS_2023 (
    BATCH_FILE_NAME VARCHAR(50),
    INDIV_INDEX VARCHAR,
    WEAPON VARCHAR(100),
    LOCATION VARCHAR(200)
);

-- =============================================================================
-- 6. HISTORICAL DATA TABLES (2020-2022)
-- Additional tables for historical use of force data analysis
-- =============================================================================

-- Historical Aggregate Summary Table (2020-2022)
CREATE OR REPLACE TABLE UOF_AGGREGATE_SUMMARY_2020_2022 (
    SECTION VARCHAR,
    CATEGORY VARCHAR,
    UNITS_OF_MEASURE VARCHAR,
    YEAR_2020 DECIMAL(10,3),
    YEAR_2021 DECIMAL(10,3),
    YEAR_2022 DECIMAL(10,3),
    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE UOF_DETAILED_DATASET_2020_2022 (
    -- Core Identification
    REPORTING_YEAR VARCHAR,  -- Changed from INTEGER to handle any format
    RECORD_ID VARCHAR,
    POLICE_SERVICE VARCHAR,
    REPORT_TYPE VARCHAR,
    TEAM_TYPE VARCHAR,
    NUMBER_POLICE_OFFICERS_INVOLVED VARCHAR,  -- Changed from INTEGER
    ASSIGNMENT_TYPE VARCHAR,
    
    -- Incident Type Flags - Changed from INTEGER to VARCHAR to handle descriptions
    TYPE_INCIDENT_ALARM VARCHAR,
    TYPE_INCIDENT_BREAK_ENTER VARCHAR,
    TYPE_INCIDENT_DOMESTIC_DISTURBANCE VARCHAR,  -- This was causing "Domestic Disturbance" error
    TYPE_INCIDENT_HOMICIDE VARCHAR,
    TYPE_INCIDENT_OTHER_DISTURBANCE VARCHAR,
    TYPE_INCIDENT_ROBBERY VARCHAR,
    TYPE_INCIDENT_SERIOUS_INJURY VARCHAR,
    TYPE_INCIDENT_SUSPICIOUS_PERSON VARCHAR,
    TYPE_INCIDENT_TRAFFIC VARCHAR,
    TYPE_INCIDENT_WEAPONS_CALL VARCHAR,
    TYPE_INCIDENT_OTHER VARCHAR,
    
    -- Police Presence and Context
    POLICE_PRESENCE VARCHAR,
    NUMBER_OF_POLICE_PRESENT VARCHAR,  -- Changed from INTEGER
    ATTIRE VARCHAR,
    NUMBER_OF_SUBJECTS VARCHAR,  -- Changed from INTEGER
    
    -- Subject Demographics
    RACE_SUB_ONE VARCHAR,
    RACE_SUB_TWO VARCHAR,
    RACE_SUB_THREE VARCHAR,
    RACE VARCHAR,
    
    -- Force Types Used - All changed to VARCHAR for flexibility
    TYPE_FORCE_FIREARM_DISCHARGED VARCHAR,
    TYPE_FORCE_FIREARM_DISCHARGED_RANK VARCHAR,
    TYPE_FORCE_FIREARM_DISCHARGED_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_FIREARM_POINTED_UNKNOWN VARCHAR,
    TYPE_FORCE_FIREARM_POINTED_AT_PERSON_RANK VARCHAR,
    TYPE_FORCE_FIREARM_POINTED_AT_PERSON_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_HANDGUN_DRAWN VARCHAR,
    TYPE_FORCE_HANDGUN_DRAWN_RANK VARCHAR,
    TYPE_FORCE_HANDGUN_DRAWN_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_LLF_DISCHARGED VARCHAR,
    TYPE_FORCE_LLF_POINTED_UNKNOWN VARCHAR,
    TYPE_FORCE_CEW VARCHAR,
    TYPE_FORCE_IMPACT_WEAPON_HARD VARCHAR,
    TYPE_FORCE_IMPACT_WEAPON_HARD_RANK VARCHAR,
    TYPE_FORCE_IMPACT_WEAPON_HARD_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_IMPACT_WEAPON_SOFT VARCHAR,
    TYPE_FORCE_IMPACT_WEAPON_SOFT_RANK VARCHAR,
    TYPE_FORCE_IMPACT_WEAPON_SOFT_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_AEROSOL VARCHAR,
    TYPE_FORCE_AEROSOL_WEAPON_RANK VARCHAR,
    TYPE_FORCE_AEROSOL_WEAPON_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_EMPTY_HAND_HARD VARCHAR,
    TYPE_FORCE_EMPTY_HAND_TECHNIQUES_HARD_RANK VARCHAR,
    TYPE_FORCE_EMPTY_HAND_TECHNIQUES_HARD_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_EMPTY_HAND_SOFT VARCHAR,
    TYPE_FORCE_EMPTY_HAND_TECHNIQUES_SOFT_RANK VARCHAR,
    TYPE_FORCE_EMPTY_HAND_TECHNIQUES_SOFT_FORCE_EFFECTIVE VARCHAR,
    TYPE_FORCE_PHYSICAL_FORCE VARCHAR,
    TYPE_FORCE_OTHER VARCHAR,
    TYPE_FORCE_OTHER_RANK VARCHAR,
    TYPE_FORCE_OTHER_FORCE_EFFECTIVE VARCHAR,
    
    -- Reason for Force - All changed to VARCHAR
    REASON_FORCE_EFFECT_ARREST VARCHAR,
    REASON_FORCE_PROTECT_SELF VARCHAR,
    REASON_FORCE_PROTECT_PUBLIC VARCHAR,
    REASON_FORCE_PREVENT_ESCAPE VARCHAR,
    REASON_FORCE_ACCIDENTAL VARCHAR,
    REASON_FORCE_PREVENT_COMMISSION_OF_OFFENCE VARCHAR,
    REASON_FORCE_PROTECT_OTHER_OFFICER VARCHAR,
    REASON_FORCE_PROTECT_SUBJECT VARCHAR,
    REASON_FORCE_OTHER VARCHAR,
    
    -- Firearm Types - All changed to VARCHAR
    TYPE_FIREARM_REVOLVER_CHECK VARCHAR,
    TYPE_FIREARM_REVOLVER_NUMBER_ROUNDS VARCHAR,
    TYPE_FIREARM_RIFLE_CHECK VARCHAR,
    TYPE_FIREARM_RIFLE_NUMBER_ROUNDS VARCHAR,
    TYPE_FIREARM_SEMI_AUTOMATIC_CHECK VARCHAR,
    TYPE_FIREARM_SEMI_AUTOMATIC_NUMBER_ROUNDS VARCHAR,
    TYPE_FIREARM_SHOTGUN_CHECK VARCHAR,
    TYPE_FIREARM_SHOTGUN_NUMBER_ROUNDS VARCHAR,
    TYPE_FIREARM_OTHER_CHECK VARCHAR,
    TYPE_FIREARM_OTHER_NUMBER_ROUNDS VARCHAR,
    
    -- Distance and Strategies
    DIST_SUB_ONE VARCHAR,
    DIST_SUB_TWO VARCHAR,
    DIST_SUB_THREE VARCHAR,
    ALTERNATIVE_STRATEGIES_CONCEALMENT VARCHAR,
    ALTERNATIVE_STRATEGIES_COVER VARCHAR,
    ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION VARCHAR,
    ALTERNATIVE_STRATEGIES_OTHER VARCHAR,
    
    -- Weapons Carried by Subjects - All changed to VARCHAR
    WEAPONS_CARRIED_SUBJECT_BASEBALL_BAT_CLUB_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_BASEBALL_BAT_CLUB_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_BASEBALL_BAT_CLUB_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_KNIFE_EDGED_WEAPON_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_KNIFE_EDGED_WEAPON_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_KNIFE_EDGED_WEAPON_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_REVOLVER_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_REVOLVER_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_REVOLVER_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_RIFLE_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_RIFLE_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_RIFLE_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_SEMI_AUTOMATIC_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_SEMI_AUTOMATIC_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_SEMI_AUTOMATIC_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_SHOTGUN_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_SHOTGUN_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_SHOTGUN_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_NONE_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_NONE_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_NONE_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_UNKNOWN_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_UNKNOWN_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_UNKNOWN_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_OTHER_SUBJECT_ONE VARCHAR,
    WEAPONS_CARRIED_SUBJECT_OTHER_SUBJECT_TWO VARCHAR,
    WEAPONS_CARRIED_SUBJECT_OTHER_SUBJECT_THREE VARCHAR,
    WEAPONS_CARRIED_FIREARM VARCHAR,
    WEAPONS_CARRIED_KNIFE_EDGED_WEAPON VARCHAR,
    WEAPONS_CARRIED_IMPACT_WEAPON VARCHAR,
    WEAPONS_CARRIED_UNARMED VARCHAR,
    WEAPONS_CARRIED_UNKNOWN_WEAPON VARCHAR,
    WEAPONS_CARRIED_OTHER_WEAPON VARCHAR,
    
    -- Weapon Locations - All changed to VARCHAR
    LOCATION_SUBJECT_WEAPONS_AT_HAND_SUBJECT_ONE VARCHAR,
    LOCATION_SUBJECT_WEAPONS_AT_HAND_SUBJECT_TWO VARCHAR,
    LOCATION_SUBJECT_WEAPONS_AT_HAND_SUBJECT_THREE VARCHAR,
    LOCATION_SUBJECT_WEAPONS_CONCEALED_PERSON_SUBJECT_ONE VARCHAR,
    LOCATION_SUBJECT_WEAPONS_CONCEALED_PERSON_SUBJECT_TWO VARCHAR,
    LOCATION_SUBJECT_WEAPONS_CONCEALED_PERSON_SUBJECT_THREE VARCHAR,
    LOCATION_SUBJECT_WEAPONS_IN_HAND_SUBJECT_ONE VARCHAR,
    LOCATION_SUBJECT_WEAPONS_IN_HAND_SUBJECT_TWO VARCHAR,
    LOCATION_SUBJECT_WEAPONS_IN_HAND_SUBJECT_THREE VARCHAR,
    TOTAL_ROUNDS_FIRED_ALL_SUBJECTS VARCHAR,
    
    -- Location Conditions - All changed to VARCHAR
    LOCATION_INCIDENT_OUTDOOR_LANEWAY VARCHAR,
    LOCATION_INCIDENT_OUTDOOR_MOTOR_VEHICLE VARCHAR,
    LOCATION_INCIDENT_OUTDOOR_PARK VARCHAR,
    LOCATION_INCIDENT_OUTDOOR_ROADWAY VARCHAR,
    LOCATION_INCIDENT_OUTDOOR_RURAL VARCHAR,
    LOCATION_INCIDENT_OUTDOOR_YARD VARCHAR,
    LOCATION_INCIDENT_OUTDOOR_OTHER VARCHAR,
    LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_APARTMENT VARCHAR,
    LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_HALLWAY VARCHAR,
    LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_HOUSE VARCHAR,
    LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_COMMERCIAL_SITE VARCHAR,
    LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_FINANCIAL_INSTITUTION VARCHAR,
    LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_PUBLIC_INSTITUTION VARCHAR,
    LOCATION_INCIDENT_INDOOR_OTHER VARCHAR,
    
    -- Weather and Lighting - All changed to VARCHAR
    WEATHER_CONDITIONS_CLEAR VARCHAR,
    WEATHER_CONDITIONS_CLOUDY VARCHAR,
    WEATHER_CONDITIONS_FOG VARCHAR,
    WEATHER_CONDITIONS_RAIN VARCHAR,
    WEATHER_CONDITIONS_SNOW_SLEET VARCHAR,
    WEATHER_CONDITIONS_SUNNY VARCHAR,
    WEATHER_CONDITIONS_OTHER VARCHAR,
    LIGHTING_CONDITIONS_DARK VARCHAR,
    LIGHTING_CONDITIONS_DAYLIGHT VARCHAR,
    LIGHTING_CONDITIONS_DUSK VARCHAR,
    LIGHTING_CONDITIONS_GOOD_ARTIFICIAL_LIGHT VARCHAR,
    LIGHTING_CONDITIONS_POOR_ARTIFICIAL_LIGHT VARCHAR,
    LIGHTING_CONDITIONS_OTHER VARCHAR,
    
    -- Injury Information
    PERSON_INJURED_SELF_MEDICAL_ATTENTION_REQUIRED VARCHAR,
    PERSON_INJURED_SELF_NATURE_INJURIES VARCHAR,
    PERSON_INJURED_OTHER_POLICE_OFFICER_MEDICAL_ATTENTION_REQUIRED VARCHAR,
    PERSON_INJURED_OTHER_POLICE_OFFICER_NATURE_INJURIES VARCHAR,
    PERSON_INJURED_THIRD_PARTY_MEDICAL_ATTENTION_REQUIRED VARCHAR,
    PERSON_INJURED_THIRD_PARTY_NATURE_INJURIES VARCHAR,
    PERSON_INJURED_SUBJECT1_MEDICAL_ATTENTION_REQUIRED VARCHAR,
    PERSON_INJURED_SUBJECT1_NATURE_INJURIES VARCHAR,
    PERSON_INJURED_SUBJECT2_MEDICAL_ATTENTION_REQUIRED VARCHAR,
    PERSON_INJURED_SUBJECT2_NATURE_INJURIES VARCHAR,
    PERSON_INJURED_SUBJECT3_MEDICAL_ATTENTION_REQUIRED VARCHAR,
    PERSON_INJURED_SUBJECT3_NATURE_INJURIES VARCHAR,
    
    -- Review Information
    REVIEWED_SUPERVISOR VARCHAR,
    REVIEWED_TRAINING_ANALYST VARCHAR
); 

-- =============================================================================
-- 7. SEMANTIC VIEW FOR SNOWFLAKE CORTEX ANALYST
-- This comprehensive view integrates all police use of force data with 
-- data dictionary context for enhanced AI analysis
-- =============================================================================

CREATE OR REPLACE VIEW UOF_SEMANTIC_VIEW AS
WITH 
-- Data Dictionary Context as Common Table Expression
data_dict AS (
    SELECT 
        VARIABLE_NAME,
        VARIABLE_LABEL,
        VARIABLE_DEFINITION,
        DATA_VALUES,
        ADDITIONAL_NOTES
    FROM ON_POLICE_USE_OF_FORCE.DATA_DICTIONARY.EN_DATA_DICTIONARY_2023
    WHERE FILE_NAME LIKE '%UoF%'
),

-- Historical Data (2020-2022) - Standardized to match 2023 structure
historical_incidents AS (
    SELECT 
        -- Unique Identifiers (using historical structure)
        h.RECORD_ID AS incident_id,
        h.RECORD_ID AS main_record_id,
        h.RECORD_ID AS individual_record_id,
        1 AS individual_index,
        
        -- Incident Context
        h.POLICE_SERVICE,
        CASE 
            WHEN h.POLICE_SERVICE LIKE '%OPP%' OR h.POLICE_SERVICE LIKE '%Ontario Provincial%' THEN 'Provincial Police Service'
            ELSE 'Local Municipal Police Service'
        END AS police_service_type_description,
        h.RECORD_ID AS incident_number,
        CAST(h.REPORTING_YEAR || '-01-01' AS DATE) AS incident_date, -- Approximate date since we only have year
        CAST('12:00:00' AS TIME) AS force_time, -- Default time since not available
        h.REPORTING_YEAR AS incident_year,
        1 AS incident_month, -- Default since not available in historical data
        1 AS incident_day_of_week, -- Default since not available
        12 AS incident_hour, -- Default since not available
        'Unknown Time Period' AS time_period,
        
        -- Location (map historical location fields to 2023 structure)
        CASE 
            WHEN h.LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_HOUSE = 1 OR 
                 h.LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_APARTMENT = 1 THEN 'Residential Building'
            WHEN h.LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_COMMERCIAL_SITE = 1 OR
                 h.LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_FINANCIAL_INSTITUTION = 1 OR
                 h.LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_PUBLIC_INSTITUTION = 1 OR
                 h.LOCATION_INCIDENT_INDOOR_OTHER = 1 THEN 'Non-Residential Building'
            WHEN h.LOCATION_INCIDENT_OUTDOOR_MOTOR_VEHICLE = 1 THEN 'Motor Vehicle'
            WHEN h.LOCATION_INCIDENT_OUTDOOR_PARK = 1 OR 
                 h.LOCATION_INCIDENT_OUTDOOR_YARD = 1 OR
                 h.LOCATION_INCIDENT_OUTDOOR_RURAL = 1 OR
                 h.LOCATION_INCIDENT_OUTDOOR_OTHER = 1 THEN 'Open Space'
            ELSE 'Unknown Location'
        END AS primary_location_type,
        
        -- Map historical incident types to 2023 structure
        CASE 
            WHEN h.TYPE_INCIDENT_DOMESTIC_DISTURBANCE = 1 THEN 'Domestic Disturbance'
            WHEN h.TYPE_INCIDENT_WEAPONS_CALL = 1 THEN 'Weapons Call'
            WHEN h.TYPE_INCIDENT_ROBBERY = 1 THEN 'Robbery'
            WHEN h.TYPE_INCIDENT_BREAK_ENTER = 1 THEN 'Break and Enter'
            WHEN h.TYPE_INCIDENT_SUSPICIOUS_PERSON = 1 THEN 'Suspicious Person'
            WHEN h.TYPE_INCIDENT_TRAFFIC = 1 THEN 'Traffic Stop'
            WHEN h.TYPE_INCIDENT_HOMICIDE = 1 THEN 'Homicide Investigation'
            WHEN h.TYPE_INCIDENT_OTHER_DISTURBANCE = 1 THEN 'Other Disturbance'
            WHEN h.TYPE_INCIDENT_ALARM = 1 THEN 'Alarm Response'
            WHEN h.TYPE_INCIDENT_SERIOUS_INJURY = 1 THEN 'Serious Injury Response'
            ELSE 'Other'
        END AS incident_type,
        
        h.ASSIGNMENT_TYPE,
        'Unknown Interaction' AS interaction_type, -- Not available in historical data
        
        -- Team and Officer Information
        h.REPORT_TYPE,
        h.TEAM_TYPE AS type_team,
        h.NUMBER_POLICE_OFFICERS_INVOLVED AS number_team,
        h.ATTIRE,
        h.NUMBER_OF_SUBJECTS AS number_individuals,
        h.NUMBER_OF_POLICE_PRESENT AS number_other_officers,
        
        -- Individual Demographics (mapping historical to 2023 structure)
        CASE 
            WHEN h.RACE IN ('White') THEN 'White'
            WHEN h.RACE IN ('Black') THEN 'Black'
            WHEN h.RACE IN ('Indigenous') THEN 'Indigenous'
            WHEN h.RACE IN ('South Asian', 'East Asian', 'Southeast Asian', 'West Asian') THEN 'Asian'
            WHEN h.RACE IN ('Latino', 'Hispanic') THEN 'Latino/Hispanic'
            WHEN h.RACE IN ('Middle Eastern') THEN 'Middle Eastern'
            ELSE 'Other/Unknown'
        END AS race_category,
        h.RACE AS specific_race,
        'Unknown Age Group' AS age_group, -- Age not available in historical detailed data
        'Unknown' AS specific_age_category,
        'Unknown' AS gender, -- Gender not explicitly available in historical data
        NULL AS difficulty_perceiving,
        
        -- Distance mapping
        COALESCE(h.DIST_SUB_ONE, 'Unknown') AS distance_between_officer_and_indiv,
        
        -- Resistance Level (map from historical force/threat indicators)
        CASE 
            WHEN h.TYPE_FORCE_FIREARM_DISCHARGED = 1 OR h.WEAPONS_CARRIED_FIREARM = 1 THEN 'Level 4: Serious Bodily Harm/Death Risk'
            WHEN h.TYPE_FORCE_EMPTY_HAND_HARD = 1 OR h.TYPE_FORCE_IMPACT_WEAPON_HARD = 1 THEN 'Level 3: Assaultive Behavior'
            WHEN h.TYPE_FORCE_PHYSICAL_FORCE = 1 OR h.TYPE_FORCE_EMPTY_HAND_SOFT = 1 THEN 'Level 2: Active Resistance'
            ELSE 'Level 1: Passive Resistance'
        END AS resistance_level,
        
        -- Weapon Information (simplified from historical structure)
        CASE WHEN h.WEAPONS_CARRIED_FIREARM = 1 THEN 'Yes' ELSE 'No' END AS perceive_access_weapon,
        
        -- Map weapons to consolidated format
        CASE 
            WHEN h.WEAPONS_CARRIED_FIREARM = 1 THEN 'Firearm'
            WHEN h.WEAPONS_CARRIED_KNIFE_EDGED_WEAPON = 1 THEN 'Knife/Edged Weapon'
            WHEN h.WEAPONS_CARRIED_IMPACT_WEAPON = 1 THEN 'Impact Weapon'
            WHEN h.WEAPONS_CARRIED_UNARMED = 1 THEN 'None'
            WHEN h.WEAPONS_CARRIED_UNKNOWN_WEAPON = 1 THEN 'Unknown'
            ELSE 'Other'
        END AS weapons_involved,
        
        CASE 
            WHEN h.WEAPONS_CARRIED_UNARMED = 1 THEN 0
            ELSE 1
        END AS weapon_count,
        
        CASE 
            WHEN h.WEAPONS_CARRIED_FIREARM = 1 THEN 'Firearm Present'
            WHEN h.WEAPONS_CARRIED_KNIFE_EDGED_WEAPON = 1 THEN 'Edged Weapon Present'
            WHEN h.WEAPONS_CARRIED_UNKNOWN_WEAPON = 1 THEN 'Unknown Weapon Type'
            ELSE 'Other Weapon Type'
        END AS weapon_category,
        'Unknown Threat Level' AS weapon_threat_level,
        
        -- Force Application Analysis (map historical to 2023 categories)
        CASE WHEN h.TYPE_FORCE_PHYSICAL_FORCE = 1 OR h.TYPE_FORCE_EMPTY_HAND_SOFT = 1 OR h.TYPE_FORCE_EMPTY_HAND_HARD = 1 THEN 1 ELSE 0 END AS physical_control_techniques_used,
        CASE WHEN h.TYPE_FORCE_CEW = 1 OR h.TYPE_FORCE_AEROSOL = 1 OR h.TYPE_FORCE_IMPACT_WEAPON_HARD = 1 OR h.TYPE_FORCE_IMPACT_WEAPON_SOFT = 1 THEN 1 ELSE 0 END AS intermediate_weapons_used,
        CASE WHEN h.TYPE_FORCE_FIREARM_DISCHARGED = 1 OR h.TYPE_FORCE_LLF_DISCHARGED = 1 THEN 1 ELSE 0 END AS lethal_weapons_used,
        
        -- Specific Force Types
        CASE WHEN h.TYPE_FORCE_PHYSICAL_FORCE = 1 THEN 'Physical Control Used' END AS physical_control_used,
        CASE WHEN h.TYPE_FORCE_CEW = 1 THEN 'CEW Used' END AS cew_used,
        CASE WHEN h.TYPE_FORCE_AEROSOL = 1 THEN 'OC Spray Used' END AS oc_spray_used,
        CASE WHEN h.TYPE_FORCE_IMPACT_WEAPON_HARD = 1 OR h.TYPE_FORCE_IMPACT_WEAPON_SOFT = 1 THEN 'Baton Used' END AS baton_used,
        CASE WHEN h.TYPE_FORCE_FIREARM_DISCHARGED = 1 THEN 'Firearm Used' END AS firearm_used,
        
        -- CEW Analysis (simplified from historical data)
        CASE WHEN h.TYPE_FORCE_CEW = 1 THEN 1 ELSE 0 END AS cew_cycles_count,
        CASE WHEN h.TYPE_FORCE_CEW = 1 THEN 'CEW Deployed' ELSE 'No CEW Usage' END AS cew_usage_pattern,
        NULL AS cew_drawn,
        NULL AS cew_pointed,
        CASE WHEN h.TYPE_FORCE_CEW = 1 THEN 'CEW Discharged' END AS cew_discharged,
        
        -- Deescalation Analysis (map from historical alternative strategies)
        CASE 
            WHEN h.ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION = 1 THEN 1
            WHEN h.ALTERNATIVE_STRATEGIES_COVER = 1 OR h.ALTERNATIVE_STRATEGIES_CONCEALMENT = 1 THEN 1
            ELSE 0
        END AS deescalation_techniques_count,
        
        CASE WHEN h.ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION = 1 THEN 'Deescalation Attempted' ELSE 'No Deescalation Attempted' END AS deescalation_attempted,
        CASE WHEN h.ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION = 1 THEN 'Directions Given' END AS directions_given,
        
        -- Reasons for Force (map historical reasons)
        CASE WHEN h.REASON_FORCE_EFFECT_ARREST = 1 THEN 'Effect Arrest' END AS reason_arrest,
        CASE WHEN h.REASON_FORCE_PREVENT_COMMISSION_OF_OFFENCE = 1 THEN 'Prevent Offence' END AS reason_prevent_offence,
        CASE WHEN h.REASON_FORCE_PREVENT_ESCAPE = 1 THEN 'Prevent Escape' END AS reason_prevent_escape,
        CASE WHEN h.REASON_FORCE_PROTECT_SELF = 1 THEN 'Protect Self' END AS reason_protect_self,
        CASE WHEN h.REASON_FORCE_PROTECT_PUBLIC = 1 THEN 'Protect Public' END AS reason_protect_public,
        CASE WHEN h.REASON_FORCE_PROTECT_OTHER_OFFICER = 1 THEN 'Protect Other Officers' END AS reason_protect_officers,
        
        -- Injury Outcomes (simplified mapping)
        'Unknown' AS officer_injury_status, -- Officer injury not detailed in historical data
        'Unknown' AS individual_injury_status, -- Individual injury not detailed in historical data
        'Unknown' AS medical_treatment_level,
        
        -- Analysis Flags
        'Historical Data' AS included_in_analysis,
        
        -- Risk Assessment
        CASE 
            WHEN h.WEAPONS_CARRIED_FIREARM = 1 AND h.TYPE_FORCE_FIREARM_DISCHARGED = 1 THEN 'Extreme Risk'
            WHEN h.WEAPONS_CARRIED_FIREARM = 1 OR h.TYPE_FORCE_FIREARM_DISCHARGED = 1 THEN 'High Risk'
            WHEN h.WEAPONS_CARRIED_KNIFE_EDGED_WEAPON = 1 OR h.TYPE_FORCE_EMPTY_HAND_HARD = 1 THEN 'Moderate Risk'
            ELSE 'Lower Risk'
        END AS calculated_risk_level,
        
        -- Force Pattern Analysis
        CASE 
            WHEN h.ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION = 1 AND h.TYPE_FORCE_PHYSICAL_FORCE = 1 THEN 'Deescalation Attempted Before Force'
            WHEN h.ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION = 0 AND h.TYPE_FORCE_EMPTY_HAND_SOFT = 1 THEN 'Limited Deescalation with Low Force'
            WHEN h.ALTERNATIVE_STRATEGIES_VERBAL_INTERACTION = 0 AND h.TYPE_FORCE_FIREARM_DISCHARGED = 1 THEN 'No Deescalation with High Force'
            ELSE 'Other Scenario'
        END AS force_escalation_pattern,
        
        -- Data Source Indicator
        'Historical (2020-2022)' AS data_source,
        h.REPORTING_YEAR AS data_year
        
    FROM UOF_DETAILED_DATASET_2020_2022 h
),

-- Main incidents with enriched context
main_incidents AS (
    SELECT 
        m.*,
        -- Add semantic labels for key fields
        CASE 
            WHEN m.POLICE_SERVICE_TYPE = 'Municipal Police' THEN 'Local Municipal Police Service'
            WHEN m.POLICE_SERVICE_TYPE = 'Ontario Provincial Police' THEN 'Provincial Police Service'
            ELSE m.POLICE_SERVICE_TYPE 
        END AS police_service_type_description,
        
        CASE 
            WHEN m.LOCATION_TYPE_RESIDENTIAL_BUILDING = 1 THEN 'Residential Building'
            WHEN m.LOCATION_TYPE_NON_RESIDENTIAL_BUILDING = 1 THEN 'Non-Residential Building'
            WHEN m.LOCATION_TYPE_MOTOR_VEHICLE = 1 THEN 'Motor Vehicle'
            WHEN m.LOCATION_TYPE_OPEN_SPACE = 1 THEN 'Open Space'
            WHEN m.LOCATION_TYPE_PUBLIC_TRANSPORTATION = 1 THEN 'Public Transportation'
            ELSE 'Unknown Location'
        END AS primary_location_type,
        
        -- Time-based analytics
        EXTRACT(YEAR FROM m.DATE) AS incident_year,
        EXTRACT(MONTH FROM m.DATE) AS incident_month,
        DAYOFWEEK(m.DATE) AS incident_day_of_week,
        EXTRACT(HOUR FROM m.APPROXIMATE_TIME_FORCE_APPLIED) AS incident_hour,
        
        -- Categorize time periods
        CASE 
            WHEN EXTRACT(HOUR FROM m.APPROXIMATE_TIME_FORCE_APPLIED) BETWEEN 6 AND 11 THEN 'Morning (6AM-12PM)'
            WHEN EXTRACT(HOUR FROM m.APPROXIMATE_TIME_FORCE_APPLIED) BETWEEN 12 AND 17 THEN 'Afternoon (12PM-6PM)'
            WHEN EXTRACT(HOUR FROM m.APPROXIMATE_TIME_FORCE_APPLIED) BETWEEN 18 AND 23 THEN 'Evening (6PM-12AM)'
            ELSE 'Night (12AM-6AM)'
        END AS time_period,
        
        -- Officer injury summary
        CASE 
            WHEN m.OFFICER_INVOLVED_INJURIES_PHYSICAL_INJURIES = 'Yes' THEN 'Officer Injured'
            ELSE 'No Officer Injury'
        END AS officer_injury_status
        
    FROM UOF_MAIN_RECORDS_2023 m
),

-- Individual records with demographic and force analysis
individual_analysis AS (
    SELECT 
        i.*,
        -- Demographic categorization
        CASE 
            WHEN i.RACE IN ('White') THEN 'White'
            WHEN i.RACE IN ('Black') THEN 'Black'
            WHEN i.RACE IN ('Indigenous') THEN 'Indigenous'
            WHEN i.RACE IN ('South Asian', 'East Asian', 'Southeast Asian', 'West Asian') THEN 'Asian'
            WHEN i.RACE IN ('Latino', 'Hispanic') THEN 'Latino/Hispanic'
            WHEN i.RACE IN ('Middle Eastern') THEN 'Middle Eastern'
            ELSE 'Other/Unknown'
        END AS race_category,
        
        -- Age group categorization
        CASE 
            WHEN i.AGE_CATEGORY = '17 and younger' THEN 'Youth (≤17)'
            WHEN i.AGE_CATEGORY IN ('18 - 24', '25 - 34') THEN 'Young Adult (18-34)'
            WHEN i.AGE_CATEGORY IN ('35 - 44', '45 - 54') THEN 'Middle Age (35-54)'
            WHEN i.AGE_CATEGORY IN ('55 - 64', '65 and older') THEN 'Older Adult (55+)'
            ELSE 'Unknown Age'
        END AS age_group,
        
        -- Force escalation analysis
        (COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_CHECK, 0) +
         COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_ESCORT_TECHNIQUES, 0) +
         COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_GROUNDING, 0) +
         COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_JOINT_LOCKS, 0) +
         COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_PINNING, 0) +
         COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_PRESSURE_POINTS, 0) +
         COALESCE(i.TYPE_FORCE_USED_PHYSICAL_CONTROL_STRIKES, 0)) AS physical_control_techniques_used,
        
        (COALESCE(i.TYPE_FORCE_USED_INTERM_WEAPON_CEW_CHECK, 0) +
         COALESCE(i.TYPE_FORCE_USED_INTERM_WEAPON_OC_CHECK, 0) +
         COALESCE(i.TYPE_FORCE_USED_INTERM_WEAPON_BATON_CHECK, 0)) AS intermediate_weapons_used,
        
        (COALESCE(i.TYPE_FORCE_USED_FIREARM_HANDGUN_CHECK, 0) +
         COALESCE(i.TYPE_FORCE_USED_FIREARM_RIFLE_CHECK, 0) +
         COALESCE(i.TYPE_FORCE_USED_FIREARM_SHOTGUN_LETHAL_CHECK, 0)) AS lethal_weapons_used,
        
        -- Deescalation attempt tracking
        (COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_COMMUNICATION, 0) +
         COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_CONTAINMENT, 0) +
         COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_COVER, 0) +
         COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_DISTANCE, 0) +
         COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_REPOSITIONING, 0) +
         COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_TEAMWORK, 0) +
         COALESCE(i.OFFICER_RESPONSES_DEESCALATION_TECHNIQUES_TIME, 0)) AS deescalation_techniques_count,
        
        -- Individual resistance level
        CASE 
            WHEN i.INDIVIDUAL_ACTIONS_SERIOUS_BODILY_HARM_DEATH = 1 THEN 'Level 4: Serious Bodily Harm/Death Risk'
            WHEN i.INDIVIDUAL_ACTIONS_ASSAULTIVE = 1 THEN 'Level 3: Assaultive Behavior'
            WHEN i.INDIVIDUAL_ACTIONS_RESISTANT_ACTIVE = 1 THEN 'Level 2: Active Resistance'
            WHEN i.INDIVIDUAL_ACTIONS_RESISTANT_PASSIVE = 1 THEN 'Level 1: Passive Resistance'
            ELSE 'Level 0: Compliant/No Resistance'
        END AS resistance_level,
        
        -- Injury outcome
        CASE 
            WHEN i.INDIV_INJURIES_PHYSICAL_INJURIES = 'Yes' THEN 'Individual Injured'
            ELSE 'No Individual Injury'
        END AS individual_injury_status,
        
        -- Medical treatment required
        CASE 
            WHEN i.INDIVIDUAL_INJURIES_TREATMENT_ADMISSION_MEDICAL_FACILITY = 1 THEN 'Hospital Admission Required'
            WHEN i.INDIVIDUAL_INJURIES_TREATMENT_MEDICAL_PERSONNEL_SCENE = 1 THEN 'Medical Personnel at Scene'
            WHEN i.INDIVIDUAL_INJURIES_TREATMENT_FIRST_AID = 1 THEN 'First Aid Only'
            WHEN i.INDIVIDUAL_INJURIES_TREATMENT_NO = 1 THEN 'No Treatment Required'
            ELSE 'Unknown Treatment'
        END AS medical_treatment_level
        
    FROM UOF_INDIVIDUAL_RECORDS_2023 i
),

-- Weapons analysis
weapons_summary AS (
    SELECT 
        w.BATCH_FILE_NAME,
        w.INDIV_INDEX,
        LISTAGG(w.WEAPON, ', ') WITHIN GROUP (ORDER BY w.WEAPON) AS weapons_involved,
        COUNT(*) AS weapon_count,
        
        -- Weapon categorization
        CASE 
            WHEN LISTAGG(w.WEAPON, ', ') LIKE '%Handgun%' OR LISTAGG(w.WEAPON, ', ') LIKE '%Long Gun%' THEN 'Firearm Present'
            WHEN LISTAGG(w.WEAPON, ', ') LIKE '%Knife%' OR LISTAGG(w.WEAPON, ', ') LIKE '%Edged%' THEN 'Edged Weapon Present'
            WHEN LISTAGG(w.WEAPON, ', ') LIKE '%Unknown%' THEN 'Unknown Weapon Type'
            ELSE 'Other Weapon Type'
        END AS weapon_category,
        
        -- Weapon accessibility
        CASE 
            WHEN LISTAGG(w.LOCATION, ', ') LIKE '%In Hand%' THEN 'Immediate Threat - Weapon in Hand'
            WHEN LISTAGG(w.LOCATION, ', ') LIKE '%On Person%' THEN 'High Threat - Weapon on Person'
            WHEN LISTAGG(w.LOCATION, ', ') LIKE '%Accessible%' THEN 'Moderate Threat - Weapon Accessible'
            ELSE 'Unknown Threat Level'
        END AS weapon_threat_level
        
    FROM UOF_WEAPONS_RECORDS_2023 w
    GROUP BY w.BATCH_FILE_NAME, w.INDIV_INDEX
),

-- CEW cycle analysis
cew_analysis AS (
    SELECT 
        c.BATCH_FILE_NAME,
        c.INDIV_INDEX,
        COUNT(*) AS cew_cycles_count,
        
        CASE 
            WHEN COUNT(*) = 1 AND MAX(c.CONDUCTED_ENERGY_WEAPON_CARTRIDGE_PROBE_CARTRIDGE_PROBE_CYCLES_CYC) LIKE '%Single Cycle%' 
                THEN 'Single Standard Cycle'
            WHEN COUNT(*) = 1 AND MAX(c.CONDUCTED_ENERGY_WEAPON_CARTRIDGE_PROBE_CARTRIDGE_PROBE_CYCLES_CYC) LIKE '%Extended%' 
                THEN 'Single Extended Cycle'
            WHEN COUNT(*) > 1 OR MAX(c.CONDUCTED_ENERGY_WEAPON_CARTRIDGE_PROBE_CARTRIDGE_PROBE_CYCLES_CYC) LIKE '%Multiple%'
                THEN 'Multiple Cycles'
            ELSE 'Unknown CEW Usage'
        END AS cew_usage_pattern
        
    FROM UOF_CYCLE_PROBE_RECORDS_2023 c
    GROUP BY c.BATCH_FILE_NAME, c.INDIV_INDEX
)

-- Combined semantic view query (Historical + Current)
SELECT 
    -- Unique Identifiers
    m.BATCH_FILE_NAME AS incident_id,
    m._ID AS main_record_id,
    i._ID AS individual_record_id,
    i.INDIV_INDEX AS individual_index,
    
    -- Incident Context
    m.POLICE_SERVICE,
    m.police_service_type_description,
    m.INCIDENT_NUMBER AS incident_number,
    m.DATE AS incident_date,
    m.APPROXIMATE_TIME_FORCE_APPLIED AS force_time,
    m.incident_year,
    m.incident_month,
    m.incident_day_of_week,
    m.incident_hour,
    m.time_period,
    m.primary_location_type,
    m.INCIDENT_TYPE AS incident_type,
    m.ASSIGNMENT_TYPE,
    m.INTERACTION_TYPE AS interaction_type,
    
    -- Team and Officer Information
    m.REPORT_TYPE,
    m.TYPE_TEAM AS type_team,
    m.NUMBER_TEAM AS number_team,
    m.ATTIRE,
    m.NUMBER_INDIVIDUALS AS number_individuals,
    m.NUMBER_OTHER_OFFICERS AS number_other_officers,
    
    -- Individual Demographics
    i.race_category,
    i.RACE AS specific_race,
    i.age_group,
    i.AGE_CATEGORY AS specific_age_category,
    i.GENDER AS gender,
    i.DIFFICULTY_PERCEIVING AS difficulty_perceiving,
    i.DISTANCE_BETWEEN_OFFICER_AND_INDIV AS distance_between_officer_and_indiv,
    
    -- Resistance and Threat Assessment
    i.resistance_level,
    i.PERCEIVE_ACCESS_WEAPON AS perceive_access_weapon,
    w.weapons_involved,
    w.weapon_count,
    w.weapon_category,
    w.weapon_threat_level,
    
    -- Force Application Analysis
    i.physical_control_techniques_used,
    i.intermediate_weapons_used,
    i.lethal_weapons_used,
    
    -- Specific Force Types (Booleans converted to descriptive text)
    CASE WHEN i.TYPE_FORCE_USED_PHYSICAL_CONTROL_CHECK = 1 THEN 'Physical Control Used' END AS physical_control_used,
    CASE WHEN i.TYPE_FORCE_USED_INTERM_WEAPON_CEW_CHECK = 1 THEN 'CEW Used' END AS cew_used,
    CASE WHEN i.TYPE_FORCE_USED_INTERM_WEAPON_OC_CHECK = 1 THEN 'OC Spray Used' END AS oc_spray_used,
    CASE WHEN i.TYPE_FORCE_USED_INTERM_WEAPON_BATON_CHECK = 1 THEN 'Baton Used' END AS baton_used,
    CASE WHEN i.TYPE_FORCE_USED_FIREARM_CHECK = 1 THEN 'Firearm Used' END AS firearm_used,
    
    -- CEW Specific Analysis
    c.cew_cycles_count,
    c.cew_usage_pattern,
    CASE WHEN i.TYPE_FORCE_USED_INTERM_WEAPON_CEW_DRAWN = 1 THEN 'CEW Drawn' END AS cew_drawn,
    CASE WHEN i.TYPE_FORCE_USED_INTERM_WEAPON_CEW_POINTED = 1 THEN 'CEW Pointed' END AS cew_pointed,
    CASE WHEN i.TYPE_FORCE_USED_INTERM_WEAPON_CEW_DISCHARGED = 1 THEN 'CEW Discharged' END AS cew_discharged,
    
    -- Deescalation Analysis
    i.deescalation_techniques_count,
    CASE WHEN i.OFFICER_RESPONSES_ATTEMPT_DEESCALATION = 'Yes' THEN 'Deescalation Attempted' 
         WHEN i.OFFICER_RESPONSES_ATTEMPT_DEESCALATION = 'No' THEN 'No Deescalation Attempted'
         END AS deescalation_attempted,
    CASE WHEN i.OFFICER_RESPONSES_DIRECTIONS_TO_COMPLY = 'Yes' THEN 'Directions Given' END AS directions_given,
    
    -- Reasons for Force
    CASE WHEN i.REASON_USE_OF_FORCE_EFFECT_ARREST = 1 THEN 'Effect Arrest' END AS reason_arrest,
    CASE WHEN i.REASON_USE_OF_FORCE_PREVENT_OFFENCE = 1 THEN 'Prevent Offence' END AS reason_prevent_offence,
    CASE WHEN i.REASON_USE_OF_FORCE_PREVENT_ESCAPE = 1 THEN 'Prevent Escape' END AS reason_prevent_escape,
    CASE WHEN i.REASON_USE_OF_FORCE_PROTECT_SELF = 1 THEN 'Protect Self' END AS reason_protect_self,
    CASE WHEN i.REASON_USE_OF_FORCE_PROTECT_PUBLIC = 1 THEN 'Protect Public' END AS reason_protect_public,
    CASE WHEN i.REASON_USE_OF_FORCE_PROTECT_OTHER_OFFICERS = 1 THEN 'Protect Other Officers' END AS reason_protect_officers,
    
    -- Injury Outcomes
    m.officer_injury_status,
    i.individual_injury_status,
    i.medical_treatment_level,
    
    -- Analysis Flags
    m.INCLUSION_SOLGEN_ARA_ANALYSIS AS included_in_analysis,
    
    -- Calculated Risk Factors
    CASE 
        WHEN w.weapon_threat_level LIKE '%Immediate%' AND i.resistance_level LIKE '%Level 4%' THEN 'Extreme Risk'
        WHEN w.weapon_threat_level LIKE '%High%' OR i.resistance_level LIKE '%Level 3%' THEN 'High Risk'
        WHEN w.weapon_threat_level LIKE '%Moderate%' OR i.resistance_level LIKE '%Level 2%' THEN 'Moderate Risk'
        ELSE 'Lower Risk'
    END AS calculated_risk_level,
    
    -- Force Appropriateness Indicators
    CASE 
        WHEN i.deescalation_techniques_count > 0 AND i.resistance_level NOT LIKE '%Level 0%' THEN 'Deescalation Attempted Before Force'
        WHEN i.deescalation_techniques_count = 0 AND i.resistance_level LIKE '%Level 1%' THEN 'Limited Deescalation with Low Resistance'
        WHEN i.deescalation_techniques_count = 0 AND i.resistance_level LIKE '%Level 4%' THEN 'No Deescalation with High Threat'
        ELSE 'Other Scenario'
    END AS force_escalation_pattern,
    
    -- Data Source Indicator
    'Current (2023)' AS data_source,
    2023 AS data_year

FROM main_incidents m
INNER JOIN individual_analysis i ON m.BATCH_FILE_NAME = i.BATCH_FILE_NAME
LEFT JOIN weapons_summary w ON i.BATCH_FILE_NAME = w.BATCH_FILE_NAME AND i.INDIV_INDEX = w.INDIV_INDEX
LEFT JOIN cew_analysis c ON i.BATCH_FILE_NAME = c.BATCH_FILE_NAME AND i.INDIV_INDEX = c.INDIV_INDEX

UNION ALL

-- Historical Data (2020-2022) with same column structure
SELECT * FROM historical_incidents;

-- =============================================================================
-- 8. PDF TECHNICAL REPORTS PROCESSING - SIMPLIFIED APPROACH
-- Using Snowflake Cortex native functions for PDF processing and chunking
-- =============================================================================

-- Stage for PDF technical reports (with directory enabled)
CREATE OR REPLACE STAGE UOF_TECHNICAL_REPORTS_STAGE
DIRECTORY = (ENABLE = TRUE)
COMMENT = 'Stage for police use of force technical reports, research papers, and policy documents';

-- ---------- INGEST PDF ----------
-- Extract text from all PDFs in the stage using Cortex Parse Document
CREATE OR REPLACE TABLE UOF_TECHNICAL_REPORTS_RAW AS 
SELECT 
    RELATIVE_PATH, 
    TO_VARCHAR (
        SNOWFLAKE.CORTEX.PARSE_DOCUMENT (
            '@UOF_TECHNICAL_REPORTS_STAGE',
            RELATIVE_PATH, 
            {'mode': 'LAYOUT'} ) : content
        ) AS EXTRACTED_CONTENT
FROM
    DIRECTORY('@UOF_TECHNICAL_REPORTS_STAGE');

-- ---------- CHUNK PDF ----------
-- Split extracted content into searchable chunks using Cortex
CREATE OR REPLACE TABLE UOF_TECHNICAL_REPORTS_PROCESSED AS
SELECT 
    -- Unique ID for each chunk (for search service linking)
    CONCAT(relative_path, '_chunk_', c.index) AS chunk_id,
    
    -- Title for search results (filename + chunk number)
    CONCAT(
        REGEXP_REPLACE(relative_path, '.*/([^/]+)$', '\\1'), -- Extract filename only
        ' (Chunk ', 
        c.index + 1, 
        ')'
    ) AS title,
    
    relative_path,
    BUILD_SCOPED_FILE_URL(@UOF_TECHNICAL_REPORTS_STAGE, relative_path) AS file_url,
    c.value::TEXT AS chunk, 
    'English' AS language,
    
    -- Add document categorization based on filename
    CASE 
        WHEN UPPER(relative_path) LIKE '%POLICY%' THEN 'Policy Document'
        WHEN UPPER(relative_path) LIKE '%RESEARCH%' OR UPPER(relative_path) LIKE '%STUDY%' THEN 'Research Study'
        WHEN UPPER(relative_path) LIKE '%REPORT%' THEN 'Technical Report'
        WHEN UPPER(relative_path) LIKE '%GUIDELINE%' OR UPPER(relative_path) LIKE '%STANDARD%' THEN 'Guidelines'
        WHEN UPPER(relative_path) LIKE '%TRAINING%' THEN 'Training Material'
        ELSE 'Other Document'
    END AS document_category
FROM
    UOF_TECHNICAL_REPORTS_RAW,
    LATERAL FLATTEN(SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
        EXTRACTED_CONTENT,
        'markdown',
        2000, -- chunks of 2000 characters each 
        300 -- 300 characters of overlap per chunk
    )) c;

-- ---------- CREATE CORTEX SEARCH SERVICE ----------
CREATE OR REPLACE CORTEX SEARCH SERVICE UOF_TECHNICAL_REPORTS_SEARCH_SERVICE
    ON chunk
    ATTRIBUTES chunk_id, title, relative_path, file_url, language, document_category
    WAREHOUSE = 'COMPUTE_WH' -- Replace with your warehouse name
    TARGET_LAG = '30 days'
    AS (
        SELECT
            chunk_id,      -- ID COLUMN: Unique identifier for linking
            title,         -- TITLE COLUMN: Display name for search results  
            chunk,         -- SEARCH CONTENT: The actual text to search
            relative_path, 
            file_url,      -- HYPERLINK COLUMN: Direct link to source document
            language,
            document_category
        FROM UOF_TECHNICAL_REPORTS_PROCESSED
    );

